version: "3"
services:
  fyp_nginx:
    container_name: fyp_nginx
    image: nginx:alpine
    volumes:
      - ./nginx/local.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      # - fyp_backend
      - fyp_db
      # - fyp_frontend
    networks:
      - net

  fyp_backend:
    container_name: fyp_backend
    image: node:17-alpine
    volumes:
      - ./backend:/app/backend
    working_dir: /app/backend
    command: sh -c 'npm install && npm start'
    ports:
      - '3001:3001'
    environment:
      - PORT=3001
    depends_on:
      - fyp_db
    networks:
      - net


  fyp_db: 
    container_name: fyp_db
    image: mysql:8.0
    ports: 
      - "3306:3306"
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=zP8c4eE8OcQX2Q6H
    volumes:
      # script to be run on every container creation
      - ./database/init.sql:/docker-entrypoint-initdb.d/init-script.sql
      - fyp_mysql:/var/lib/mysql
    networks:
      - net

  
  # fyp_frontend:
  #   container_name: fyp_frontend
  #   # stdin_open: true
  #   image: node:17-alpine
  #   volumes:
  #     - ./room-booking-frontend:/app/frontend
  #   working_dir: /app/frontend
  #   command: sh -c 'npm install && npm start'
  #   ports:
  #     - '3000:3000'
  #   links: 
  #     - backend
  #   networks:
  #     - net

volumes:
  fyp_mysql:

networks:
  net: