export const UserType = {
  STUDENT: 'student',
  ADMIN: 'admin',
}

export const ApiRequestType = {
  LOGIN: 'LOGIN',
  GET_USER_INFO: 'GET_USER_INFO',
  GET_PROJECT_LIST: 'GET_PROJECT_LIST',
  POST_FYP: 'POST_FYP',
  POST_FYP_MANY: 'POST_FYP_MANY',
  PUT_FYP: 'PUT_FYP',
  DELETE_FYP: 'DELETE_FYP',
  POST_USER: 'POST_USER',
  PUT_USER: 'PUT_USER',
  POST_USER_MANY: 'POST_USER_MANY',
  GET_USER: 'GET_USER',
  DELETE_USER: 'DELETE_USER',
  DELETE_RESERVATION: 'DELETE_RESERVATION',
  POST_RESERVATION: 'POST_RESERVATION',
  GET_RESERVATION: 'GET_RESERVATION',
  OPEN_SELECTION: 'OPEN_SELECTION',
  CLOSE_SELECTION: 'CLOSE_SELECTION',
}

export const options = [
  'Add FYP',
  'Edit FYP',
  'Add User',
  'Edit User',
  'FYP Selection',
  'Generate Report',
]
